
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-currency-app
  labels:
    app: currency-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: currency-app
  template:
    metadata:
      labels:
        app: currency-app
    spec:
      containers:
        - name: currency-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.containerPort }}"
