
version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: currency-backend
    ports:
      - "8080:5000"         # host:container
    environment:
      - PORT=5000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        # זה השם של השירות docker-compose, לא localhost!
        - VITE_API_BASE=http://localhost:8080
    container_name: currency-frontend
    ports:
      - "3000:80"           # frontend נגיש ב-http://localhost:3000
    depends_on:
      - backend


# docker-compose build
# docker-compose up


# docker-compose down      # לעצור ולנקות
# docker-compose build     # חשוב כי שינינו ARG של build
# docker-compose up